### ISSUE TITLE
代码规范待制定

### ISSUE THREAD

**Issue by Charley-Hsu** [tgoufe/CyanMapleDesign#5]
代码规范待制定，目前代码检查无法通过，协同开发易出问题 @qqkillqq

**Comment by royIdoodle** [comment]
建议用`styleLint`来对scss部分进行代码检查来实现代码规范。
可以`ZensUI`的`.stylelintrc`文件：
`.stylelintrc`地址：https://github.com/ZensFE/ZensUI/blob/master/.stylelintrc
`.stylelintignore`地址：https://github.com/ZensFE/ZensUI/blob/master/.stylelintignore
